### ISSUE TITLE
[Feature Request] show delta of ticket sold between this and last entries of data

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycontw-kktix-tracking-bot#3]
Currently the bot shows the data like:

```
PyCon TW 2021 目前售票狀況為：
-------------- 主活動 --------------
- 個人票：107
- 企業票：45
- 保留票：140
- 總售票人數：292 / 800
-------------- 子活動 --------------
- Sprint：7 / 80
```

 Is it a good idea if the bot provides additional information like:

```
PyCon TW 2021 目前售票狀況為：
-------------- 主活動 --------------
- 個人票：107 (+1 in 2 days)
- 企業票：45 (+0 in 2 days)
- 保留票：140 (+0 in 2 days)
- 總售票人數：292 / 800 (+1 in 2 days)
-------------- 子活動 --------------
- Sprint：7 / 80 (+0 in 2 days)
```

**Comment by allen91wu** [comment]
Hi @tai271828 thank you for your suggestion.
I am trying to write a beta feature. And implement the code on our staff discord server. I will make the code more comprehensive and then push the code.

This features will be like following messages:
```
PyCon TW 2021 08/31 售票狀況：
-------------- 主活動 --------------
- 個人票：123 (+8 in last 24 hours)
- 企業票：59 (+7 in last 24 hours)
- 保留票：140 (+0 in last 24 hours)
總售票人數：322 / 800 (+15 in last 24 hours)
-------------- 子活動 --------------
- Sprint：15 / 80  (+ 6 in last 24 hours)
```

The bot will send the messages every day. And compare the tickets sold with yesterday. If you think the interval is too short or have any problems, please let me know.

**Comment by tai271828** [comment]
The bot has been running for a few days and we all love it. Thank you @allen91wu !!
